export default {
  INITAIL_SCREEN: 'initailScreen',
  LOGIN: 'login',
  SIGNUP: 'signUp',
  HOME: 'home',
  PROFILE: 'profile',
  CREATE_POST: 'createPost',
  SEARCH: 'search',
  NOTIFICATION: 'notification',
  TAB_ROUTES: 'tabRoutes',
  User_Profile: 'UserProfile',
  Message: 'Message',
  ChatList: 'ChatList',
  CreateGroup: 'CreateGroup',
  GroupChatScreen: 'GroupChatScreen',
  AllGroups: 'AllGroups',
  COMMENT: 'Comment',
  Followers: 'Followers',
};
